---
title: "R Notebook"
output: html_notebook
---


```{r}
install.packages("emojifont")

install.packages("waffle", repos = "https://cinc.rud.is")

```

```{r}
library(tidyverse)
library(hrbrthemes)
library(waffle)
library(emojifont)


```

```{r}
school_diversity <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-09-24/school_diversity.csv")

```

```{r}
attach()

school_diversity %>% group_by(ST,SCHOOL_YEAR) %>% 
  summarize(mean_asian = mean(Asian))
```

```{r}
names(school_diversity
      )
```


```{r}
agg_data <- school_diversity %>% 
  #select(LEAID ,AIAN  ,Asian ,Black,Hispanic,White, Multi ) %>% 
  gather(key = "race", value = "percentage",AIAN  ,Asian ,Black,Hispanic,White, Multi ) %>% 
  #filter(SCHOOL_YEAR == '1994-1995') %>% 
  group_by(SCHOOL_YEAR,race) %>% 
  summarise(mean_perc = mean(percentage,na.rm = T)) %>% 
  mutate(mean_perc_int = as.integer(round(mean_perc)))


agg_data

```
```{r}
agg_data %>% 
  filter(SCHOOL_YEAR != '1994-1995') %>% 
  mutate(race = fct_reorder(race,mean_perc_int)) %>% 
  ggplot(aes(fill = race,values = mean_perc_int)) +
geom_waffle(n_rows = 10, size = 2.03, colour = "white", flip = F) +
  scale_x_discrete() + 
    scale_y_continuous(labels = function(x) x * 10, # make this multiplyer the same as n_rows
                     expand = c(0,0)) +
  
    scale_x_discrete(expand=c(0,0)) +
  scale_y_discrete(expand=c(0,0)) +
    theme_enhance_waffle() +
  #theme_ipsum_rc(grid="") +
  ggthemes::scale_fill_tableau(name=NULL) +
  coord_equal()

  #facet_wrap(~SCHOOL_YEAR,ncol = 1)



```

```{r}

agg_data_1 <- agg_data %>% 
  unnest() %>% 
  ungroup() %>% 
  filter(SCHOOL_YEAR != '1994-1995') %>%
  select(-SCHOOL_YEAR) %>% 
  mutate(names = race,
         vals = mean_perc_int) %>% 
  select(names,vals)
  
  

as.vector(agg_data_1)
waffle(agg_data_1,legend_pos = "bottom") +
  theme_classic()
```



```{r fig.height=5, fig.width=10, message=FALSE, warning=F}
extrafont::font_install() 
extrafont::loadfonts()
extrafont::font_install()


agg_data %>% 
  filter(SCHOOL_YEAR != '1994-1995') %>% 
  mutate(race = fct_reorder(race,mean_perc_int),
         label = emoji('camel')) %>% 
  ggplot(aes(values = mean_perc_int)) +
  geom_pictogram(n_rows = 10, aes(label = label,colour = race), flip = TRUE, make_proportional = TRUE) +
 
  scale_x_discrete() + 
   # scale_y_continuous(labels = function(x) x * 10, # make this multiplyer the same as n_rows
     #                expand = c(0,0)) +
  
    scale_x_discrete(expand=c(0,0)) +
  scale_y_discrete(expand=c(0,0)) +
    theme_enhance_waffle() +
  #theme_ipsum_rc(grid="") +
  ggthemes::scale_fill_tableau(name=NULL) +
  coord_equal() 



```


```{r}
school_diversity %>% 
  #select(LEAID ,AIAN  ,Asian ,Black,Hispanic,White, Multi ) %>% 
  gather(key = "race", value = "percentage",AIAN  ,Asian ,Black,Hispanic,White, Multi ) %>% 
  filter(SCHOOL_YEAR != '1994-1995') %>% 
  group_by(race) %>% 
  summarise(mean_perc = mean(percentage,na.rm = T))
```


```{r}

set.seed(123)
x <- rnorm(10)
set.seed(321)
y <- rnorm(10)
plot(x, y, cex=0)
text(x, y, labels=emoji('cow'), cex=1.5, col='steelblue', family='EmojiOne')

d <- data.frame(x=x, y=y,
     label = sample(c('\U0001F601', emoji('camel')), 10, replace=TRUE),
     type = sample(LETTERS[1:3], 10, replace=TRUE))

library("ggplot2")
ggplot(d, aes(x, y, color=type, label=label)) +
    geom_text(family="EmojiOne", size=6)
```

