---
title: "Simpsons Guest Stars"
output: html_notebook
---
## I borrowed a few tips from Amelia Barber. you can check her repo
  https://github.com/ameliabedelia/tidy_tuesday
I also used

```{r}
remotes::install_git("https://git.rud.is/hrbrmstr/ggchicklet.git")

library(tidyverse)
library(hrbrthemes)
library(tidytext)
library(cowplot)
library(tvthemes)

```
## I used an additional dataset from data.world:
https://data.world/data-society/the-simpsons-by-the-data/

```{r}

simpson_episodes <- read_csv('~/data-society-the-simpsons-by-the-data/simpsons_episodes.csv')

simpsons <- readr::read_delim("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-08-27/simpsons-guests.csv", delim = "|", quote = "")


```



```{r}
head(simpson_episodes)
```

```{r}

simpsons_merged<- simpsons %>% 
    left_join(simpson_episodes,by = 'production_code')


  ```
```{r}
names(simpsons_merged)
```
```{r}
most_frequent_guest_stars <- simpsons_merged %>% 
  count(guest_star,sort = TRUE) %>% 
  filter(n>10) %>% 
  pull(guest_star)
most_frequent_guest_stars
```


```{r fig.height = 7, fig.width = 12,dpi=1000}

simpsons_palette <- c(
    "#FC0209", # bart red
    "#FFCC00", #orange
    "#fed90f", # simpsons yellow
    "#46732EFF", # Flanders green 
   "#0363C3", # marge blue
    "#d1b271", # lightbrownbeige
    "#7A491E" # beige 

)
cut_labels <- c('5 - 5.5',
                '5.5 - 6',
                '6 - 6.5',
                '6.5 - 7',
                '7 - 7.5',
                '7.5 - 8',
                '8 - 8.5',
                '8.5 - 9',
                '9 - 9.5')


g <- simpsons_merged %>% 
  filter(guest_star %in% most_frequent_guest_stars,season.x != 'Movie',!is.na(imdb_rating)) %>% 
  
  mutate(season.x  = parse_number(season.x )) %>% 
  
  group_by(season.x,guest_star) %>% 
  summarize(avg_rating = mean(imdb_rating),
            avg_viewers = mean(us_viewers_in_millions),
            n_appearances = n()) %>% 
  mutate(n_viewers = cut(avg_viewers,breaks  = c(0,10,20,30,40,50)),
         ratings = cut(avg_rating, breaks = seq(5,9.5,0.5) , labels = cut_labels ))  %>% 
  filter(!is.na(n_viewers)) %>% 
  ggplot(aes(season.x, y = guest_star,fill =ratings )) +
  geom_point(aes(size = n_appearances),shape = 23) +
  geom_text(aes(label = n_appearances),size = 3) +
  labs(y = NULL, x = NULL,
    title = "Most Frequent Simpsons Guest Stars and Their Average Viewership by Season") +
  scale_size(range = c(5, 9)) +
  scale_x_continuous(breaks = c(1,5,10,15,20,25))+
  scale_fill_manual(name ="Ratings:", values = rev(simpsons_palette)) +
  
  theme_simpsons()+
  theme_minimal_grid(font_family = "Akbar") +
  theme(panel.grid.major = element_blank(),
        plot.title = element_text( size = 18, face = "bold"),
        legend.title = element_text( size = 14, face = "bold")) +
  guides(size=FALSE,fill = guide_legend(override.aes = list(size = 5)))



ggsave('Plots/1.jpg',plot = g,height = 6, width = 12,dpi=1000)
g

```
```{r fig.height = 6, fig.width = 10,dpi=1000}
simpsons_palette <- c(
    "#FC0209", # bart red
    "#fed90f" # simpsons yellow
)


arrows <- tibble(
  x1 = c(14 ),
  x2 = c(11),
  y1 = c(7  ),
  y2 = c(5.5)
)


g <- simpsons_merged %>% 
  group_by(guest_star) %>% 
  summarize(avg_rating = mean(imdb_rating),
            avg_viewers = mean(us_viewers_in_millions),
            n_appearances = n()) %>% 
  arrange(avg_rating) %>% 
  slice(1:20) %>% 
  mutate(guest_star = fct_reorder(guest_star,avg_viewers,.desc = TRUE)) %>%
  mutate(gs = case_when(guest_star == "Lady Gaga" ~ "Lady Gaga",
                        
                        TRUE~''
                        )) %>% 
  ggplot(aes(x =guest_star,y = avg_viewers )) +
  geom_col(aes(fill = gs),show.legend = FALSE) +
  scale_fill_manual(values = rev(simpsons_palette)) +
  
 geom_text(data = . %>% mutate(avg_viewers = avg_viewers+0.3),aes(label = avg_rating,y=avg_viewers),family = "Akbar")+
      annotate("text", x = 16, y = 7., label = 'The lowest IMDB rating goes to "Lady Gaga"\nfor playing  herself in the "Lisa Goes Gaga" episode ', family = "Akbar", size = 4.5,vjust = 0.5,hjust = 0.6) +
    geom_curve(data = arrows, aes(x = x1, y = y1, xend = x2, yend = y2),
             arrow = arrow(length = unit(0.07, "inch")), size = 1,
             color = "gray50", curvature = -0.2) +
coord_flip() +
      labs(y = "Average Number of Viewers in the US\n(in millions)", x = NULL,
         title = "Worst Rated Guest Stars in Simpsons and their Average Viewership") +
  theme_simpsons() +
  theme_minimal_grid(font_family = "Akbar") +
  theme(panel.grid.major = element_blank(),
        ) 


ggsave('Plots/2.jpg',plot = g,height = 6, width = 10,dpi=1000)
g

```


```{r fig.height = 6, fig.width = 12,dpi=1000}


simpsons_palette <- c(

    "#0363C3", # marge blue,
    "#fed90f" # simpsons yellow

)

arrows <- tibble(
  x1 = c(12 ),
  x2 = c(8),
  y1 = c(24),
  y2 = c(22)
)
arrows_2 <- tibble(
  x1 = c(14 ),
  x2 = c(16),
  y1 = c(24 ),
  y2 = c(18)
)

g <- simpsons_merged %>% 
  group_by(guest_star) %>% 
  summarize(avg_rating = mean(imdb_rating),
            avg_viewers = mean(us_viewers_in_millions),
            n_appearances = n()) %>% 
  arrange(desc(avg_rating)) %>% 
  slice(1:20) %>% 
  mutate(guest_star = fct_reorder(guest_star,avg_viewers,.desc = TRUE)) %>%
  mutate(ar = case_when(avg_rating == 9~'top',
                        
                        TRUE~ ''
                        )) %>% 
  ggplot(aes(x =guest_star,y = avg_viewers )) +
  geom_col(aes(fill = ar),show.legend = FALSE) +
  scale_fill_manual(values = rev(simpsons_palette)) +
  geom_text(data = . %>% mutate(avg_viewers = avg_viewers+0.5),aes(label = avg_rating,y=avg_viewers),family = "Akbar")+
      annotate("text", x = 13, y = 23, label = ' Guest stars with\nthe highest IMDB ratings', family = "Akbar", size = 4,vjust = 0.5,hjust = 0.5) +
    geom_curve(data = arrows, aes(x = x1, y = y1, xend = x2, yend = y2),
             arrow = arrow(length = unit(0.07, "inch")), size = 1,
             color = "gray50", curvature = -0.5) +
  
      geom_curve(data = arrows_2, aes(x = x1, y = y1, xend = x2, yend = y2),
             arrow = arrow(length = unit(0.07, "inch")), size = 1,
             color = "gray50", curvature = 0.5) +
  coord_flip() +
  labs(y = "Average Number of Viewers in the US\n(in millions)", x = NULL,
        title = "Top Rated Guest Stars in Simpsons and their Average Viewership") +
  coord_flip() +
  theme_simpsons() +
  theme_minimal_grid(font_family = "Akbar") +
  theme(panel.grid.major = element_blank()) 


ggsave('Plots/3.jpg',plot = g,height = 6, width = 12,dpi=1000)
g
```

