---
title: "School Diversity"
output: html_notebook
---


```{r}
#install.packages("emojifont")

#install.packages("waffle", repos = "https://cinc.rud.is")

```

```{r}
library(tidyverse)
library(hrbrthemes)
library(waffle)
library(emojifont)
library(cowplot)


```

```{r}
school_diversity <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-09-24/school_diversity.csv")

tt <-  tidytuesdayR::tt_load('2019-09-24')
tt
```

```{r}
names(school_diversity)
```


```{r}
school_diversity_group_by_state <- school_diversity %>% 
  pivot_longer(AIAN :Multi,names_to  = "race", values_to  = "proportion" ) %>% 
  group_by(ST,SCHOOL_YEAR,race) %>% 
  summarise(mean_proportion = mean(proportion ,na.rm = T)) %>% 
  mutate(mean_proportion_int = as.integer(round(mean_proportion))) %>% 
  replace_na(list(mean_proportion_int = 0))

school_diversity_group_by_country <- school_diversity %>% 
  pivot_longer(AIAN :Multi,names_to  = "race", values_to  = "proportion" ) %>% 
  group_by(SCHOOL_YEAR,race) %>% 
  summarise(mean_proportion = mean(proportion ,na.rm = T)) %>% 
  mutate(mean_proportion_int = as.integer(round(mean_proportion))) %>% 
  replace_na(list(mean_proportion_int = 0))
```



```{r fig.height=35, fig.width=25, message=FALSE, warning=FALSE}


colors <- c(
  'AIAN' = '#577590',
  'Asian' = '#43AA8B',
  'Black' = '#F3722C',
  'Hispanic' = '#F94144',
  'Multi' = '#90BE6D',
  'White' = '#F9C74F'
)
g_state <- school_diversity_group_by_state %>%
  filter(SCHOOL_YEAR != '1994-1995', ST != 'ID') %>%
  mutate(race = fct_reorder(race, mean_proportion_int)) %>%
  ggplot(aes(fill = race, values = mean_proportion_int)) +
  geom_waffle(
    n_rows = 10,
    size = 2.03,
    colour = "white",
    flip = F
  ) +
  scale_x_discrete(expand = c(0, 0)) +
  scale_y_discrete(expand = c(0, 0)) +
  
  theme_enhance_waffle() +
  scale_fill_manual(values = colors) +
  facet_wrap(~ ST, ncol = 5) +
  coord_equal() +
  theme(strip.text = element_text(family =  'Montserrat', size = 18),
        legend.position = 'none')

```


```{r fig.height=35, fig.width=25, message=FALSE, warning=FALSE}




g_country <- school_diversity_group_by_country %>%
  filter(SCHOOL_YEAR != '1994-1995') %>%
  mutate(race = fct_reorder(race, mean_proportion_int)) %>%
  ggplot(aes(fill = race, values = mean_proportion_int)) +
  geom_waffle(
    n_rows = 10,
    size = 2.03,
    colour = "white",
    flip = F
  ) +
  scale_x_discrete(expand = c(0, 0)) +
  scale_y_discrete(expand = c(0, 0)) +
  
  guides(fill = guide_legend(override.aes = list(alpha = 0.9, size = 12))) +
  labs(fill = '') +
  theme_enhance_waffle() +
  scale_fill_manual(values = colors) +
  coord_equal() +
  theme(
    strip.text = element_text(family =  'Montserrat',
                              
                              size = 18),
    legend.position = 'top',
    plot.title = element_text(size = 40,
                              margin = ggplot2::margin(0, 0, 30, 0)),
    plot.subtitle = element_text(size = 25),
    legend.direction = 'horizontal',
    legend.text = element_text(size = 15, family =  'Montserrat')
  )


```

```{r message=FALSE, warning=FALSE}
g_combinded <- plot_grid(g_country,g_state,nrow = 2,rel_heights = c(0.2,0.8))
```



```{r fig.height=3,fig.width=20}
title <- ggdraw() +draw_label('School Diversity in the US During the 2016-2017 School Year',fontface = 'bold',size = 30,hjust =0.5) 

subtitle<- ggdraw() +draw_label('This plot illustrates the average racial distribution of students in the US and accross different US States',fontface = 'bold',size = 20,hjust =0.5,color = 'grey20')


```


```{r fig.height=40,fig.width=20, message=FALSE, warning=FALSE}
plot_grid(title,subtitle,g_combinded,nrow = 3,rel_heights = c(0.02,0.02,0.8)) 

```

