---
title: "R Notebook"
output: html_notebook
---


```{r}

library(tidyverse)
library(ggthemes)
library(png)
library(gridGraphics)
library(cowplot)
library(hrbrthemes)
library(ggtext)
library(ggdark)


```

```{r}
df_cpu <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-09-03/cpu.csv")
df_gpu <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-09-03/gpu.csv")
df_ram <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-09-03/ram.csv")
```


## Again I borrowed some codes from Cédric Scherer's wonderful repository:

https://github.com/Z3tt/TidyTuesday/blob/master/R/2019_36_MooresLaw.Rmd

```{r}
df_opt <-
  df_cpu %>% 
  mutate(year_cum = date_of_introduction %/% 2 * 2) %>% 
  group_by( year_cum) %>% 
  summarize(transistor_count = mean(transistor_count, na.rm = T)) %>% 

  mutate(
    min = min(transistor_count, na.rm = T),
    start = min(year_cum, na.rm = T),
    lev = 2^(year_cum / 2 - start / 2),
    opt = min * lev)
  

df_opt
```





```{r}
df_cpu_modified %>% 
  group_by(year_cum) %>% 
  summarize(media  = mean(transistor_count))
```


```{r}

df_cpu_modified <-df_cpu %>% 
  filter(!is.na(transistor_count)) %>% 
  mutate(year_cum = date_of_introduction %/% 2 * 2,
       opt =  2250 * 2^(year_cum / 2 - 1970 / 2),
       pioneers_bool = ifelse(transistor_count>=opt,TRUE,FALSE) )


df_cpu_pioneers <- df_cpu_modified %>% 
  filter(pioneers_bool) %>% 
  mutate( text_position_y = case_when(designer == 'Microsoft/AMD' ~ 	 82718592000,
                                designer == 'Intel' & date_of_introduction == 2012 ~ 82718592000,
                           TRUE ~ 1.3 * transistor_count   ),
       text_position_x= case_when(designer == 'Microsoft/AMD' ~ year_cum +1.5 ,
                                  designer == 'Intel' & date_of_introduction == 2012~ year_cum -1.5 ,
                           TRUE ~ year_cum - 0.9) )
df_cpu_others <- df_cpu_modified %>% 
  filter(!pioneers_bool)

```



```{r }


arrow_intel <- tibble(
  x1 = c(2012 ),
  x2 = c(2010),
  y1 = c( 4718592000 ),
  y2 = c(52718592000)
)

arrow_mic_amd <- tibble(
  x1 = c(2012),
  x2 = c(2013),
  y1 = c( 4718592000 ),
  y2 = c(52718592000)
)
moore_arrow  <- tibble(
  x1 = c(1996),
  x2 = c(1990),
  y1 = c( 18432000 ),
  y2 = c(78432000)
)
 
mean_arrow  <- tibble(
  x1 = c(1998),
  x2 = c(2002),
  y1 = c( 9473000  ),
  y2 = c(314730)
)


g <- ggplot() +

  geom_point(data = df_cpu_pioneers, aes(x = year_cum, y = transistor_count ,color = designer ),alpha = 0.6,size = 3,shape = 16) +
  
  geom_text(data = df_cpu_pioneers, aes(label = designer, x = text_position_x  ,y = text_position_y ),size = 3.5 ,family = "Montserrat",color = 'grey75') +
  scale_color_tableau() +
  
  geom_curve(data = arrow_intel, aes(x = x1, y = y1, xend = x2, yend = y2),
             arrow = arrow(length = unit(0.08, "inch")), size = 0.5,
             color = "grey65", curvature = -0.1) +

  geom_curve(data = arrow_mic_amd, aes(x = x1, y = y1, xend = x2, yend = y2),
             arrow = arrow(length = unit(0.08, "inch")), size = 0.5,
             color = "grey65", curvature = -0.1) +


  
  
   

  geom_point(data = df_cpu_others, aes(x = year_cum, y = transistor_count ),color = 'chocolate',alpha = 0.4) +
        scale_y_log10(breaks = c(1, 10^3, 10^6, 10^9, 10^12),
                  labels = scales::comma) +
  
  
  
  stat_summary(data = df_cpu_modified,aes(x = year_cum,y = transistor_count ), fun.y = mean, geom = "line", size = 1,color = "#30d59f",alpha = 0.8 ) +
  
  annotate("text", x = 2002, y = 1.747300e+05, label = "Average number of\ntransistors" ,color =  "#30d59f",family = "Montserrat",size = 4,alpha = 0.8) +
  geom_curve(data = mean_arrow, aes(x = x1, y = y1, xend = x2, yend = y2),
             arrow = arrow(length = unit(0.08, "inch")), size = 0.5,
             color = "#30d59f", curvature = -0.1) + 
  

  geom_line(data = df_opt,aes(year_cum, y = opt),color = 'indianred') +
  annotate("text", x = 1990, y = 168432000, label = "Prediction of\n Moore's Law" ,color = 'indianred',family = "Montserrat",size = 4,alpha = 0.8) +
  geom_curve(data = moore_arrow, aes(x = x1, y = y1, xend = x2, yend = y2),
             arrow = arrow(length = unit(0.08, "inch")), size = 0.5,
             color = "indianred", curvature = -0.1) +
  scale_y_log10(breaks = c(1, 10^3, 10^6, 10^9, 10^12),
                  labels = scales::comma) +
  scale_x_continuous(breaks = c(seq(1970,2019,10),2018),
                     labels = c(seq(1970,2019,10),2018))+
   
  
  labs(x = NULL, y = "Number of Transistors",     title = "MOORE'S LAW and the Number of Transistor in CPUs", 
       subtitle = "Only a handful of pioneer companies have been able to keep up with the Moore's Law", caption = "Source: Wikipedia -Visualization by Muhammad Nakhaee @m_cnakhaee  ") +
  dark_theme_bw(base_family  = 'Montserrat')  +   
  theme(axis.text = element_text(family = "Montserrat",
                                   size = 13),
      axis.title.y = element_text(family = "Montserrat", 
                                      face = "plain",
                                      size = 13,
                                      color = "white",
                                  vjust = 1,
                                  hjust = 0.5),

      plot.title = element_text(family = "Montserrat", 
                                  size = 20, 
                                  color = "white"),
      plot.subtitle = element_text(family = "Montserrat", 
                                  size = 15, 
                                  color = "white"),
      plot.caption = element_text(family = "Montserrat", 
                                  size = 11, 
                                  color = "grey"),
          line = element_blank(),
          legend.position = "none",
        )  
  
     

ggsave('Plots/CPU.jpg',plot = g,height = 10, width = 20,dpi=1000)


```


