---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
library(ggridges)
library(ggthemes)
library(ggraph)
library(tidygraph)
library(igraph)
library(hrbrthemes)

```


```{r}
tuesdata <- tidytuesdayR::tt_load('2020-01-14') 
tuesdata <- tidytuesdayR::tt_load(2020, week = 3)
passwords <- tuesdata$passwords
passwords
```

```{r fig.height=20,fig.width=10}
passwords_letters <- passwords %>% 
  filter(!is.na(password)) %>% 
  filter(strength<11) %>% 
  mutate(let1 = substr(password,1,1),
         let2 = substr(password,2,2),
         let3 = substr(password,3,3),
         let4 = substr(password,4,4),
         let5 = substr(password,5,5),
         let6 = substr(password,6,6),
         let7 = substr(password,7,7),
         let8 = substr(password,8,8),
         let9 = substr(password,9,9))


g <- passwords_letters %>% 
  filter(strength < 11,
         strength>0) %>% 
  rename(Strength = strength) %>% 
  pivot_longer(let1:let9,names_to = 'letters',values_to = 'let') %>%
  filter(let!='') %>%  
  ggplot(aes(x = let ,fill = Strength)) +
  geom_bar(position = 'identity') +
  scale_fill_continuous_tableau()+
  facet_wrap(Strength~.,nrow = 15, labeller = label_both,scales='free') +
  labs(x = '',
       y= '',
       title = 'The Anatomy of Password Quality',
       subtitle = "Distribution of characters used in passwords and password strength (quality) where\n 10 indicates the highest quality passwords and 1 the lowest."
       )+
  theme_tufte() +
  theme_modern_rc() +
  theme(
      plot.title = element_text(
      family = 'Montserrat',
      face = "bold",
      size = 25,
      hjust = 0.5
    ),
    plot.subtitle = element_text(
      family = 'Montserrat',
      size = 15,
      hjust = 0.5
    ),
    axis.text.y.left = element_text(
      family = 'Montserrat',
      size = 10,
      hjust = 0.5
    ),
    axis.text.x = element_text(
      family = 'Montserrat',
      size = 12,
      hjust = 0.5
    ),
    strip.text = element_text(
      family = 'Montserrat',
      size = 13,
      hjust = 0.5,
      color = 'gray'
    ),
    legend.position = 'none',
    strip.background = element_rect(color = 'gray50')
  )

ggsave("password_quality.jpg", 
 plot = g, 
 width = 10, height = 20)

g
```

### Other Plots

```{r fig.height=10,fig.width=10}



passwords_letters  %>%
  mutate(from = let1, to = let2) %>%
  rbind(passwords_letters  %>%
          mutate(from = let2, to = let3)) %>%
  rbind(passwords_letters  %>%
          mutate(from = let3, to = let4)) %>%
  rbind(passwords_letters  %>%
          mutate(from = let4, to = let5)) %>%
  rbind(passwords_letters  %>%
          mutate(from = let5, to = let6)) %>%
  rbind(passwords_letters  %>%
          mutate(from = let6, to = let7)) %>%
  rbind(passwords_letters  %>%
          mutate(from = let7, to = let8)) %>%
  rbind(passwords_letters  %>%
          mutate(from = let8, to = let9)) %>%
  group_by(from, to) %>%
  summarize(n_ = n() / 100,
            avg_strength = mean(strength)) %>%
  select(from, to, n_, avg_strength) %>%
  graph_from_data_frame() %>%
  create_layout(layout = "circle") %>%
  ggraph() +
  #geom_edge_fan() +
  geom_edge_link(aes(alpha = n_)) +
  #geom_edge_arc()+
  geom_node_point(aes(color = name %in% letters)) +
  geom_node_text(aes(label = name), repel = TRUE, size = 10) +
  #geom_edge_loop(aes(alpha = n_),direction = 180,span =90) +
  theme_void()


```



```{r}
passwords %>% 
  filter(strength<11) %>% 
  mutate(len_pass = nchar(password)) %>% 
  ggplot(aes(x = strength, y = category,fill =category )) +
  labs(fill = '')+
  geom_density_ridges() +
  theme_tufte()+
  scale_fill_gdocs()
```

