---
title: "R Notebook"
output: html_notebook
---



```{r}
sf_trees <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-28/sf_trees.csv')
head(sf_trees)

```
```{r}
library(tidyverse)
library(lubridate)
library(sf)


```
```{r}

```

```{r}
sf_map <- read_sf('E:/map data/norcal-latest-free.shp/gis_osm_roads_free_1.shp')

head(sf_map)

```
```{r}
lat <- 37.7749#center point latitude
long <- -122.4194   #center point longitude
crs1 <- 102013
crs2 <- 4326
dist <- 2000


pt <- data.frame(lat = lat, long = long)
pt <- pt %>% st_as_sf(coords = c("long", "lat"), crs = 4326) %>%  st_transform(4326) 
circle <- st_buffer(pt, dist = dist)
circle <- circle %>% st_transform(st_crs(sf_map))
sf_roads <- st_intersection(circle, sf_map)

head(sf_roads)
```

```{r}
ggplot()+
  geom_sf(data = sf_roads) +
  geom_point(data = sf_trees,aes(x = latitude, y = longitude ))
-```
```


```{r}

ggplot()+
  geom_sf(data = sf_roads) +
  geom_point(sf_trees,aes(x = latitude, y = longitude ))
